# ============================================
# DEFAULT CONFIGURATION (??? ????????? ??????????)
# ============================================

# ????????? (?? ??????????????!)
env=default

# === ????????? ????????? ===
api.base.url=http://localhost:8080
api.base.path=/api/v1

ui.base.url=https://ya.ru

# === browser config ===
browser.mode=local
browser.name=chrome
browser.version=latest
browser.timeout=15000
browser.size=1920x1080
browser.headless=false

# Selenoid (mode=selenoid)
browser.selenoid.url=http://localhost:4444/wd/hub
browser.selenoid.vnc=true
browser.selenoid.video=false
browser.selenoid.log=true